const fs = require('fs');
const path = require('path');

const POSIX_SCENARIOS_DIR = 'sample-data/scenarios';
const scenariosDir = path.resolve(POSIX_SCENARIOS_DIR);

function listDirEntries(dirPath, prefix = '') {
  return fs
    .readdirSync(dirPath)
    .filter((item) => item.startsWith(prefix))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));
}

function getScenarios() {
  const scenarios = [];
  const items = listDirEntries(scenariosDir, 'scen-');
  for (const scenId of items) {
    const scenPath = path.join(scenariosDir, scenId);
    if (!fs.statSync(scenPath).isDirectory()) continue;
    const label = `Scenario ${scenId.split('-')[1]}`;
    const states = [];
    const stateItems = listDirEntries(scenPath, 'state-');
    for (const stateId of stateItems) {
      const statePath = path.join(scenPath, stateId);
      if (!fs.statSync(statePath).isDirectory()) continue;
      const stateLabel = `State ${stateId.split('-')[1]}`;
      const files = [];

      function collectFiles(dirFsPath, relativePosix) {
        const dirEntries = fs
          .readdirSync(dirFsPath)
          .sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));

        for (const entry of dirEntries) {
          const fullPath = path.join(dirFsPath, entry);
          const nextRelative = relativePosix
            ? path.posix.join(relativePosix, entry)
            : entry;
          if (fs.statSync(fullPath).isDirectory()) {
            collectFiles(fullPath, nextRelative);
          } else if (entry.toLowerCase().endsWith('.xml')) {
            files.push(nextRelative);
          }
        }
      }

      collectFiles(statePath, stateId);
      states.push({ id: stateId, label: stateLabel, files });
    }
    scenarios.push({ id: scenId, label, states });
  }
  return { basePath: POSIX_SCENARIOS_DIR, scenarios };
}

const index = getScenarios();
const jsonOutput = JSON.stringify(index, null, 2);
fs.writeFileSync(path.join(scenariosDir, 'index.json'), `${jsonOutput}\n`);
fs.writeFileSync(
  path.join(scenariosDir, 'index.js'),
  `// Auto-generated by make build-index\nexport default ${jsonOutput};\n`,
);
console.log('index manifest rebuilt');
